### ISSUE TITLE
Feature Request: Display URL to project

### ISSUE THREAD

**Issue by velddev** [top-gg/crowdin-discord#4]
Would be cool for this project to show a link to the project 😄 I left an example of how it could look. Let me know what you guys think

![image](https://user-images.githubusercontent.com/13852840/119028368-aabb2300-b9a7-11eb-8b6a-5d49c8e66aed.png)

**Comment by shivaco** [comment]
Sounds convenient.

**Comment by goverfl0w** [comment]
Looks better and more readable as a webhook event this way.
